---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть мультиязычный (английский/русский языки), то есть при выборе языка контент сайта должен отображаться на выбранном языке
  - Выбранный пользовавтелем язык должен храниться в сессии браузера
  - При фильтрации товаров по категории, список производителей должен отображаться в соответствии с выбранной котегорией товаров
  - При оформлении заказа должны запрашиваться контактые данные пользователя и адрес доставки
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - После успешной оплаты заказа должно появиться сообщение об успешном оформлении заказа
  - После оформления заказа пользователь должен иметь возможность ознакомиться с данными об оформленном заказе и его статусом (передан в доставку/доставлен)
  - После оформления заказа корзина должна обнуляться
  - Пользователь должен иметь возможность ставить рейтинг товарам