---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность просматривать на странице товара и в каталоге название товаров, их рейтинг, цену товаров со скидкой и без нее
  - Пользователь должен иметь возможность добавлять товары в корзину, просматривать содержимое корзины и продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность удалять товары из корзины и продолжить выбирать товары в каталоге 
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть SPA-приложением, которое не перезагружает страницу
implicit:
  - Сайт должен быть мультиязычный (английский/русский языки), то есть при выборе языка контент сайта должен отображаться на выбранном языке
  - Выбранный пользовавтелем язык должен храниться в сессии браузера
  - При фильтрации товаров по категории, список производителей должен отображаться в соответствии с выбранной категорией товаров
  - При оформлении заказа должны запрашиваться контактые данные пользователя и адрес доставки
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - После успешной оплаты заказа должно появиться сообщение об успешном оформлении заказа
  - После оформления заказа пользователь должен иметь возможность ознакомиться с данными об оформленном заказе и его статусом (передан в доставку/доставлен)
  - После оформления заказа корзина должна обнуляться
  - Пользователь должен иметь возможность ставить рейтинг товарам